### PR TITLE
FIP-35579: Update npm and merge released (tagged) version back to dev branch.

### PR DESCRIPTION
**Pull request by destinf**
https://financeit.atlassian.net/browse/FIP-35579

Financeit PR for testing: https://github.com/financeit/financeit/pull/13552

### CODE REVIEW

**Comment by destinf** [comment]
Financeit tests to confirm passing: https://gitlab.com/financeitcanada/dev/financeit/-/pipelines/205331978

**Comment by destinf** [comment]
@johndrwood, this is a two parter, going to have to merge these changes to `dev` branch, then tag this, and then change Financeit to point to the correct version

**Review by johndrwood — APPROVED** [review]
@destinf not sure how well tested the parts of the app that use these components. Would be good to get QA to do a manual run through of the partner settings sections.

**Comment by johndrwood** [comment]
@destinf is there any difference now between our fork and the main repo?

**Comment by destinf** [comment]
@johndrwood Turns out there are definitely a few changes. I didn't realize we versioned off the "novalidate_form" branch instead of master.

**Comment by johndrwood** [comment]
> @johndrwood Turns out there are definitely a few changes. I didn't realize we versioned off the "novalidate_form" branch instead of master.

Ah, ok thanks @destinf

**Pull request merged**
